--
-- 0006_t026_schema_gaps.sql — closes the 4 Área 01 schema gaps (T-026,
-- order-state-machine/spec.md + serialised-inventory-operations/spec.md)
--
-- SDD artifacts (design.md, specs/*, audits/, rehearsals/) live at the mhans workspace root:
-- ../../../openspec/changes/consolidado-web-2027/ (OUTSIDE this repo — not visible from a clone
-- of `dashboard/` alone; see R2-003). Full option analysis:
-- ../../../openspec/changes/consolidado-web-2027/apply-progress.md, "Decisiones de schema
-- pendientes (T-026)".
--
-- USER DECISION (2026-08-23), all four gaps resolved as Opción A:
--
--   1. Check-In            -> new table `asset_movements`, FK to `serialised_assets` (0004).
--      One row per physical checkout/checkin against an order. This is also the numerator half
--      of gap 4 (availability): an asset with an open checkout (a 'checkout' row with no later
--      'checkin' row) is unavailable; everything else in `serialised_assets` is available.
--   2. Conductor/Pago Delivery -> nullable columns directly on `shipping_usage` (already 1:1
--      with `orders` via its UNIQUE `order_id`, already has RLS + grants defined). One driver,
--      one payment per delivery — no `delivery_assignments` table.
--   3. Rentabilidad (minimal scope) -> `acquisition_cost` on `serialised_assets` (cost per
--      physical unit) + a new `expenses` table for operational spend not tied to a unit
--      (maintenance, transport, etc.). Deliberately NOT in scope: `recurring_expenses` and a
--      monthly P&L view (Opción B) — not a MUST of `proposal.md`, deferred to a later change if
--      the user prioritises full financial reporting.
--   4. Inventory denominator -> no table beyond #1. `serialised_assets` (0004) is already the
--      denominator (one row per physical unit); `asset_movements` (#1) is the numerator. Closed
--      as a side effect of #1, per the recommendation in apply-progress.md.
--
-- ORDERING. Lands after `0005_revoke_public_default_privileges.sql` (current chain head), so both
-- new tables are deny-by-default at creation for every grantee, on top of the explicit REVOKEs
-- this migration also carries (belt-and-braces, satisfies `lint-chain.sh` rule 2).
--
-- HERMES_RO POSTURE. Neither new table is granted to `hermes_ro`. `asset_movements` carries the
-- same "inventory-security data, no MCP call site" reasoning 0004 wrote for `serialised_assets` —
-- check-in/checkout records are dashboard-only. `expenses` is financial data with no read path in
-- `rental-mcp/rental_mcp/server.py` today. Per 0004's convention: do not add a grant here without
-- an ADR-D8 allowlist change and a matching update to
-- `hermes-mhans/scripts/assert-least-privilege.sh`. The two `ALTER TABLE ... ADD COLUMN` changes
-- below (on `serialised_assets` and `shipping_usage`) need no grant statement at all: Postgres
-- table privileges are not column-scoped here (no column-level GRANT was ever issued on either
-- table), so the existing table-level grants continue to cover the new columns unchanged.
-- `shipping_usage` was never on the 0002 `hermes_ro` allowlist (8 relations, `shipping_usage` is
-- not one of them), so adding columns to it changes nothing about hermes_ro's posture either.
--
-- IDENTITY, NOT SERIAL. Both new tables use `GENERATED ALWAYS AS IDENTITY`, per the sequence-grant
-- gotcha documented in `RESTORE_RUNBOOK.md` ("Sequences need their own grant... Prefer
-- `GENERATED BY DEFAULT AS IDENTITY`... no sequence privilege" needed beyond the table grant).
-- `serialised_assets` (0004) set this precedent; this migration follows it for both new tables.
--
-- POST-REVIEW FIXES (R1, 2026-08-23; no BLOCKER/CRITICAL, 2 WARNINGs fixed before this migration
-- was ever applied to any database):
--
--   R1-001 — `expenses.category` was free text with only a non-empty CHECK, deviating from this
--   project's classification-field convention: every other classification column in the schema is
--   a bounded enum CHECK (`user_profiles.tipo_cliente`, `coupons.discount_type`,
--   `shipping_methods.shipping_type`, and this very migration's own `asset_movements.direction`).
--   Fixed to an enum CHECK sourced from the canonical Rentabilidad HTML's `#g-cat` <select>
--   (`CONSOLIDADO WEB YEYSON/Área 01 · Rental Técnico/OFF/
--   MarioHans_OS_Area01_Rentabilidad_Canonical_RC2.1.2.html`, "Gastos Fijos" + "Gastos Variables"
--   optgroups), translated to English tokens per the condition-vocabulary convention 0004
--   established (English code, Spanish UI label): Fijos -> warehouse (Bodega), internet
--   (Internet), payroll (Sueldos), accounting (Contador), software (Software), hosting (Hosting);
--   Variables -> delivery (Delivery), transport (Transporte), maintenance (Mantención), repair
--   (Reparación), supplies (Insumos).
--
--   R1-002 — `asset_movements.checked_by` was free text in a table that declares itself an audit
--   trail, with no anchor to verifiable identity — anyone could type any name. Fixed to
--   `checked_by_admin_id`, a nullable FK to `admin_users(id)` ON DELETE SET NULL. Chosen over
--   keeping a free-text display name alongside the FK: the canonical Check-In/Devoluciones HTML
--   (`MarioHans_OS_Area01_CheckIn_Devoluciones_Canonical_RC2.1.2.html`) has no "revisado por" /
--   "responsable" free-text field to justify one, and the dashboard's `withAuth` middleware
--   already resolves the acting admin from `admin_users` on every request (`.claude/rules/
--   01-api-patterns.md`: "user tiene: id, email, role") — the API route can pass that id straight
--   through with no extra input, so a free-text column would only invite an unverified value with
--   no upside. ON DELETE SET NULL, not RESTRICT: an admin account being removed must not block
--   deleting/blocking that admin, nor silently corrupt historical movement rows — the row survives
--   as an anonymised movement rather than the delete failing.
--
-- POST-REVIEW FIXES (R3, on commit 4de3c5c, 2026-08-23; CRITICAL fixed in the service layer,
-- this WARNING fixed here):
--
--   R3-102 — the app-level "no double checkout" rule (`assetMovementService.ts` reading a
--   history, then inserting) has a TOCTOU race: two concurrent checkout requests for the same
--   asset can both read "nothing open" before either insert commits, and both succeed. An
--   append-only audit trail cannot fix this by mutating a checkout row's own event fields
--   (direction/checked_at must stay exactly what happened), so the guard is a separate nullable
--   `closed_by_movement_id` marker plus a partial UNIQUE index: at most one row per asset can have
--   `direction = 'checkout' AND closed_by_movement_id IS NULL` at a time. Two concurrent INSERTs
--   of an open checkout for the same asset now serialize at the index itself — the second one
--   gets a 23505 unique-violation, which `assetMovementService.ts` maps to the same
--   `MOVEMENT_TRANSITION_ERRORS.OPEN_CHECKOUT_EXISTS` message the synchronous history check
--   already throws (R3-103's single-sourced constant in `lib/assetMovements.ts`). The marker is
--   set by an AFTER INSERT trigger on the matching checkin (see `asset_movements_close_checkout`
--   below), which also re-asserts "a checkin must close an open checkout" at the DB layer as a
--   second line of defense behind the app-level check.
--
-- Idempotent: IF NOT EXISTS / IF EXISTS throughout, so a partial apply can be replayed.
--

SET lock_timeout = '5s';
SET statement_timeout = '30s';

BEGIN;

-- =========================================================================
-- ROLE GUARD (prod-parity audit, 2026-08-19). Runs FIRST, inside the transaction. See
-- 0002/0004 for the full rationale: production's `public` relations are owned by
-- `supabase_admin`, and `postgres` there is neither superuser nor a member of that role, so a
-- wrong-role apply of ALTER/REVOKE/GRANT/POLICY statements either errors loudly or (worse, for
-- REVOKE) reports success while changing nothing.
--
-- Apply with:  psql -U supabase_admin -v ON_ERROR_STOP=1 -f <this file>
-- =========================================================================
DO $role_guard$
BEGIN
  IF NOT pg_has_role(current_user, 'supabase_admin', 'USAGE') THEN
    RAISE EXCEPTION
      'Esta migracion debe ejecutarse como supabase_admin (rol actual: %). Las relaciones de public '
      'pertenecen a supabase_admin: como postgres, REVOKE informa exito y no revoca nada.',
      current_user
      USING HINT = 'psql -U supabase_admin -v ON_ERROR_STOP=1 -f <archivo>';
  END IF;
END
$role_guard$;

-- =========================================================================
-- Gap 1 — asset_movements (Check-In numerator + availability numerator, gap 4)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.asset_movements (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    asset_id            bigint      NOT NULL REFERENCES public.serialised_assets(id) ON DELETE RESTRICT,
    order_id            integer     NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
    direction           text        NOT NULL CHECK (direction IN ('checkout', 'checkin')),
    condition_notes     text,
    checked_by_admin_id bigint      REFERENCES public.admin_users(id) ON DELETE SET NULL,
    checked_at          timestamptz NOT NULL DEFAULT now()
);

-- ON DELETE RESTRICT on the asset/order FKs, matching 0004's reasoning for
-- serialised_assets -> products: a movement record is the audit trail of what happened to a
-- physical unit on an order. Deleting either side must not silently erase that history.
-- `checked_by_admin_id` is ON DELETE SET NULL instead (R1-002): removing an admin account must
-- not block on, or corrupt, historical movement rows — the row survives as an anonymised
-- movement rather than the delete failing.

COMMENT ON TABLE public.asset_movements IS
    'One checkout or checkin event of a serialised_assets unit against an order. T-026 gap 1/4.';

CREATE INDEX IF NOT EXISTS asset_movements_asset_id_idx
    ON public.asset_movements (asset_id);

CREATE INDEX IF NOT EXISTS asset_movements_order_id_idx
    ON public.asset_movements (order_id);

-- Partial: most movement rows will carry an admin id, but the FK is nullable (R1-002 ON DELETE
-- SET NULL path), so a partial index keeps "movements by admin" lookups narrow.
CREATE INDEX IF NOT EXISTS asset_movements_checked_by_admin_id_idx
    ON public.asset_movements (checked_by_admin_id) WHERE checked_by_admin_id IS NOT NULL;

-- Availability query shape (gap 4 denominator/numerator): "assets with an open checkout" is
-- `asset_id NOT IN (SELECT asset_id FROM asset_movements WHERE direction = 'checkin' ...)` joined
-- against the latest checkout per asset. This partial index keeps that scan narrow — most rows
-- will eventually be 'checkin', so indexing only 'checkout' rows keeps the index small relative to
-- the full table as history accumulates.
CREATE INDEX IF NOT EXISTS asset_movements_open_checkout_idx
    ON public.asset_movements (asset_id, checked_at DESC) WHERE direction = 'checkout';

REVOKE ALL ON TABLE public.asset_movements FROM PUBLIC;
REVOKE ALL ON TABLE public.asset_movements FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.asset_movements TO service_role;

ALTER TABLE public.asset_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service_role full access to asset_movements" ON public.asset_movements;
CREATE POLICY "Allow service_role full access to asset_movements"
    ON public.asset_movements
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- -------------------------------------------------------------------------
-- R3-102 — DB-level guard against a TOCTOU double-open-checkout (see the header note above for
-- the full rationale). `closed_by_movement_id` is set on a checkout row by the checkin that
-- closes it; NULL means "still open".
-- -------------------------------------------------------------------------
ALTER TABLE public.asset_movements
    ADD COLUMN IF NOT EXISTS closed_by_movement_id bigint
        REFERENCES public.asset_movements(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.asset_movements.closed_by_movement_id IS
    'Set on a checkout row by the checkin movement that closes it. NULL = still open. T-026 R3-102.';

-- The actual concurrency guard: at most one row per asset can be an unmatched (open) checkout.
-- Two concurrent INSERTs of a second open checkout for the same asset serialize here — the
-- second commit fails with 23505, which `assetMovementService.ts` maps to
-- MOVEMENT_TRANSITION_ERRORS.OPEN_CHECKOUT_EXISTS (R3-102b).
CREATE UNIQUE INDEX IF NOT EXISTS asset_movements_one_open_checkout_idx
    ON public.asset_movements (asset_id)
    WHERE direction = 'checkout' AND closed_by_movement_id IS NULL;

-- Fires only for checkin inserts: closes the asset's currently open checkout (if any) by setting
-- its closed_by_movement_id to the new checkin's id. Raises if there is nothing open to close —
-- the same rule `validateMovementTransition` enforces at the app layer, now also enforced here so
-- a direct INSERT bypassing the service (or a future caller) cannot skip it.
CREATE OR REPLACE FUNCTION public.asset_movements_close_checkout()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    closed_count integer;
BEGIN
    UPDATE public.asset_movements
    SET closed_by_movement_id = NEW.id
    WHERE asset_id = NEW.asset_id
      AND direction = 'checkout'
      AND closed_by_movement_id IS NULL
      AND id <> NEW.id;

    GET DIAGNOSTICS closed_count = ROW_COUNT;

    IF closed_count = 0 THEN
        RAISE EXCEPTION 'El equipo no tiene un checkout abierto para hacer check-in';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS asset_movements_close_checkout_trigger ON public.asset_movements;
CREATE TRIGGER asset_movements_close_checkout_trigger
    AFTER INSERT ON public.asset_movements
    FOR EACH ROW
    WHEN (NEW.direction = 'checkin')
    EXECUTE FUNCTION public.asset_movements_close_checkout();

-- =========================================================================
-- Gap 2 — driver + delivery payment on shipping_usage (nullable, one driver/one payment per
-- delivery per the user's decision). No grant/RLS change: shipping_usage already has RLS enabled
-- and its grants defined by 0000_baseline.sql / prior migrations; adding nullable columns does not
-- widen any existing grantee's surface.
-- =========================================================================
ALTER TABLE public.shipping_usage
    ADD COLUMN IF NOT EXISTS driver_name text,
    ADD COLUMN IF NOT EXISTS driver_phone text,
    ADD COLUMN IF NOT EXISTS delivery_payment_status text
        CHECK (delivery_payment_status IS NULL OR delivery_payment_status IN ('unpaid', 'paid')),
    ADD COLUMN IF NOT EXISTS delivery_payment_amount numeric
        CHECK (delivery_payment_amount IS NULL OR delivery_payment_amount >= 0);

COMMENT ON COLUMN public.shipping_usage.driver_name IS
    'Nombre del conductor asignado al despacho. T-026 gap 2.';
COMMENT ON COLUMN public.shipping_usage.delivery_payment_status IS
    'Estado del pago del despacho (unpaid/paid), independiente del pago de la orden. T-026 gap 2.';

-- =========================================================================
-- Gap 3 — acquisition_cost on serialised_assets (cost per physical unit). No grant change: the
-- table's grants are already scoped to service_role only (0004); a new column inherits that.
-- =========================================================================
ALTER TABLE public.serialised_assets
    ADD COLUMN IF NOT EXISTS acquisition_cost numeric
        CHECK (acquisition_cost IS NULL OR acquisition_cost >= 0);

COMMENT ON COLUMN public.serialised_assets.acquisition_cost IS
    'Costo de adquisicion del activo fisico, para margen/ROI. T-026 gap 3 (Opcion A, alcance minimo).';

-- =========================================================================
-- Gap 3 — expenses (operational spend not tied to a single physical unit's acquisition).
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.expenses (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- CATEGORY VOCABULARY (R1-001). English tokens (code), Spanish labels (UI), per the project
    -- convention (see 0004's condition vocabulary). Sourced from the canonical Rentabilidad
    -- `#g-cat` <select> (Gastos Fijos: Bodega, Internet, Sueldos, Contador, Software, Hosting;
    -- Gastos Variables: Delivery, Transporte, Mantención, Reparación, Insumos) — not an invented
    -- list. Fixed/variable is a UI grouping in the canonical, not a DB column: nothing downstream
    -- of `expenses` needs to distinguish fixed from variable spend, so it is left for the read
    -- layer (UI groups the 11 values into the same two headings) rather than added as a second
    -- enum column with no consumer.
    category         text        NOT NULL CHECK (category IN (
                         'warehouse', 'internet', 'payroll', 'accounting', 'software', 'hosting',
                         'delivery', 'transport', 'maintenance', 'repair', 'supplies'
                     )),
    amount           numeric     NOT NULL CHECK (amount >= 0),
    expense_date     date        NOT NULL,
    related_order_id integer     REFERENCES public.orders(id) ON DELETE SET NULL,
    related_asset_id bigint      REFERENCES public.serialised_assets(id) ON DELETE SET NULL,
    notes            text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ON DELETE SET NULL, unlike asset_movements/serialised_assets's RESTRICT: an expense is a
-- financial record that must survive the order or asset it references being deleted (the spend
-- already happened), so it degrades to an unlinked expense rather than blocking the delete.

COMMENT ON TABLE public.expenses IS
    'Operational expense not tied to a single asset acquisition (maintenance, transport, etc). T-026 gap 3, Opcion A minimal scope.';

CREATE INDEX IF NOT EXISTS expenses_expense_date_idx
    ON public.expenses (expense_date);

CREATE INDEX IF NOT EXISTS expenses_related_order_id_idx
    ON public.expenses (related_order_id) WHERE related_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS expenses_related_asset_id_idx
    ON public.expenses (related_asset_id) WHERE related_asset_id IS NOT NULL;

DROP TRIGGER IF EXISTS expenses_set_updated_at ON public.expenses;
CREATE TRIGGER expenses_set_updated_at
    BEFORE UPDATE ON public.expenses
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

REVOKE ALL ON TABLE public.expenses FROM PUBLIC;
REVOKE ALL ON TABLE public.expenses FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.expenses TO service_role;

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service_role full access to expenses" ON public.expenses;
CREATE POLICY "Allow service_role full access to expenses"
    ON public.expenses
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

COMMIT;

-- =========================================================================
-- Post-apply assertion (T-026 acceptance, mirrors 0004). Both rows must read `false` for EACH new
-- table; a `true` means a grant was added without review. Runtime script:
-- `hermes-mhans/scripts/assert-t026-schema-gaps-isolation.sh`.
--
--   SELECT has_table_privilege('hermes_ro', 'public.asset_movements', 'SELECT') AS ro_select,
--          has_table_privilege('anon',      'public.asset_movements', 'SELECT') AS anon_select;
--   SELECT has_table_privilege('hermes_ro', 'public.expenses', 'SELECT') AS ro_select,
--          has_table_privilege('anon',      'public.expenses', 'SELECT') AS anon_select;
-- =========================================================================
